=== sleeplacker/ling-hub/ROOT/CODE/Learn/JAVA/CORE_JAVA_II/ChapterII03_XML/src/com/ling/learn0303/validation/config.dtd
<!--元素类型定义-->
<!ELEMENT root ANY><!--ANY表示root标签中可以包含任何子元素-->
<!ELEMENT font (style,size)><!--逗号隔开表示font标签包含两个子元素，style后面跟size，顺序不能变-->
<!ELEMENT style EMPTY><!--style标签不能有子元素，包括文本元素，只能是<style></style>或<style/>的形式-->
<!ELEMENT size ANY>
<!ELEMENT name (#PCDATA)><!--name标签内容只能包含文本，不能有子元素-->
<!ELEMENT color (red|green|blue)><!--style标签只有red，green，blue中的一个子标签-->
<!ELEMENT red ANY>
<!ELEMENT green ANY>
<!ELEMENT blue ANY>
<!ELEMENT number (#PCDATA|int|double|bigdecimal)*><!--(混合内容) number标签下面可以有文本，int，double和bigdecimal任意多个，任意顺序排序-->
<!ELEMENT int ANY>
<!ELEMENT double ANY>
<!ELEMENT bigdecimal ANY>
<!ELEMENT couples (husband,wife)+><!--couples标签包含一对或者多对husband,wife标签-->
<!ELEMENT husband ANY>
<!ELEMENT wife ANY>
<!ELEMENT lover (boy,girl)?><!--lover标签包含一对零对boy,girl标签-->
<!ELEMENT boy ANY>
<!ELEMENT girl ANY>
<!ELEMENT etoken ANY>
<!ELEMENT etokens ANY>
<!ELEMENT eid ANY>
<!ELEMENT eidref ANY>
<!ELEMENT eidrefs ANY>
<!ELEMENT entityref ANY>

<!--属性类型定义
通用语法：<!ATTLIST element attribute type defaultValue>
依次表示：元素名称，属性名称，属性类型，属性默认值
-->
<!ATTLIST style prop (plain|blod|italic) "plain"><!--style标签包含属性prop，属性值可选plain，blod或italic，如果不指定属性，解析器会得到属性plain-->
<!ATTLIST style length (short|long) #REQUIRED><!--style标签包含属性length，且必输，可选short或long-->
<!ATTLIST size unit CDATA #REQUIRED>
<!ATTLIST husband desc CDATA #IMPLIED><!--husband标签包含属性desc，类型是任意字符串，且属性是可选的-->
<!ATTLIST wife desc CDATA #IMPLIED><!--desc标签包含属性desc，类型是任意字符串，且属性是可选的-->
<!ATTLIST etoken token NMTOKEN #REQUIRED><!--etoken标签包含属性token，类型标记符号(和CDATA类似，但大部分非字母数字字符和内部空白字符不允许使用)，且属性是必输的-->
<!ATTLIST etokens tokens NMTOKENS #REQUIRED><!--类型为多个NMTOKEN以空格隔开-->
<!ATTLIST eid id ID #REQUIRED><!--id类型要求同一文件不能出现相同id-->
<!ATTLIST eidref idref IDREF #REQUIRED><!--已存在id的引用类型-->
<!ATTLIST eidrefs idrefs IDREFS #REQUIRED><!--已存在id的引用列表，已空格隔开-->
<!ATTLIST entityref attr CDATA #REQUIRED>


<!--实体类型定义-->
<!ENTITY back.label "Back"><!--在其他标签属性中可以以这种方式包含实体引用：<element attr="&back.label;"/>-->

=== sleeplacker/ling-hub/ROOT/CODE/Learn/JAVA/CORE_JAVA_II/ChapterII03_XML/src/com/ling/learn0303/validation/validationTest02.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root SYSTEM "config.dtd">
<!-- 引用dtd文件 -->
<root>
	<font>
		<style length="short"></style>
		<size unit="px">36</size>
	</font>
	<name>
		ling
	</name>
	<color>
		<blue></blue>
	</color>
	<number>
		<int>11</int>
		3.1415926
		<bigdecimal>123456789.123456</bigdecimal>
		<double>12.88</double>
	</number>
	<couples>
		<husband desc="tall and handsome">ling</husband>
		<wife>txq</wife>
		<husband>lsc</husband>
		<wife desc="good mother">pmz</wife>
	</couples>
	<lover>
		<!-- <boy>zhang</boy> <girl>tang</girl> -->
	</lover>
	<!-- <etoken token="!!"/> --><!-- !!不属于NMTOKEN -->
	<etoken token="AA" />
	<etokens tokens="AA BB cc" />

	<eid id="A0001" />
	<!-- <eid id="A0001"/> --><!-- id不唯一时会报错 -->
	<eid id="A0002" />
	<eid id="A0003" />

	<eidref idref="A0001" />
	<!-- <eidref idref="A0000" /> --><!-- 如果属性中的ID在文件中没出现过会报错 -->
	<eidrefs idrefs="A0001 A0002 A0003" />

	<entityref attr="&back.label;" /><!-- 自定义实体引用 -->
	<entityref attr="&quot;" /><!-- 预定义实体引用，这里是单引号 -->
</root>

<!-- xml 要求只有一个根元素，如果出现两个跟元素，会出现下面的错误 The markup in the document following 
	the root element must be well-formed. -->
<!-- <other> </other> -->
